/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIndexRouteImport } from './routes/preview.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PreviewSplashRouteImport } from './routes/preview.splash'
import { Route as PreviewScanPayRouteImport } from './routes/preview.scan-pay'
import { Route as PreviewReferralProgramRouteImport } from './routes/preview.referral-program'
import { Route as PreviewProfileHelpRouteImport } from './routes/preview.profile-help'
import { Route as PreviewPhoneVerifiedRouteImport } from './routes/preview.phone-verified'
import { Route as PreviewPermissionsRouteImport } from './routes/preview.permissions'
import { Route as PreviewOnboardingRouteImport } from './routes/preview.onboarding'
import { Route as PreviewKycRejectedRouteImport } from './routes/preview.kyc-rejected'
import { Route as PreviewKycPendingRouteImport } from './routes/preview.kyc-pending'
import { Route as PreviewKycFlowRouteImport } from './routes/preview.kyc-flow'
import { Route as PreviewKycApprovedRouteImport } from './routes/preview.kyc-approved'
import { Route as PreviewHomeRouteImport } from './routes/preview.home'
import { Route as PreviewAuthPhoneRouteImport } from './routes/preview.auth-phone'
import { Route as DiagnosticsRoutesRouteImport } from './routes/diagnostics.routes'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminKycFollowupsRouteImport } from './routes/admin.kyc-followups'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminGeoRouteImport } from './routes/admin.geo'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminCohortsRouteImport } from './routes/admin.cohorts'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminAppImagesRouteImport } from './routes/admin.app-images'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as ApiKycVerifyRouteImport } from './routes/api/kyc.verify'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/preview/',
  path: '/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PreviewSplashRoute = PreviewSplashRouteImport.update({
  id: '/preview/splash',
  path: '/preview/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewScanPayRoute = PreviewScanPayRouteImport.update({
  id: '/preview/scan-pay',
  path: '/preview/scan-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewReferralProgramRoute = PreviewReferralProgramRouteImport.update({
  id: '/preview/referral-program',
  path: '/preview/referral-program',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProfileHelpRoute = PreviewProfileHelpRouteImport.update({
  id: '/preview/profile-help',
  path: '/preview/profile-help',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPhoneVerifiedRoute = PreviewPhoneVerifiedRouteImport.update({
  id: '/preview/phone-verified',
  path: '/preview/phone-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPermissionsRoute = PreviewPermissionsRouteImport.update({
  id: '/preview/permissions',
  path: '/preview/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewOnboardingRoute = PreviewOnboardingRouteImport.update({
  id: '/preview/onboarding',
  path: '/preview/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewKycRejectedRoute = PreviewKycRejectedRouteImport.update({
  id: '/preview/kyc-rejected',
  path: '/preview/kyc-rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewKycPendingRoute = PreviewKycPendingRouteImport.update({
  id: '/preview/kyc-pending',
  path: '/preview/kyc-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewKycFlowRoute = PreviewKycFlowRouteImport.update({
  id: '/preview/kyc-flow',
  path: '/preview/kyc-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewKycApprovedRoute = PreviewKycApprovedRouteImport.update({
  id: '/preview/kyc-approved',
  path: '/preview/kyc-approved',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewHomeRoute = PreviewHomeRouteImport.update({
  id: '/preview/home',
  path: '/preview/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAuthPhoneRoute = PreviewAuthPhoneRouteImport.update({
  id: '/preview/auth-phone',
  path: '/preview/auth-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoutesRoute = DiagnosticsRoutesRouteImport.update({
  id: '/diagnostics/routes',
  path: '/diagnostics/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycFollowupsRoute = AdminKycFollowupsRouteImport.update({
  id: '/kyc-followups',
  path: '/kyc-followups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeoRoute = AdminGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCohortsRoute = AdminCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppImagesRoute = AdminAppImagesRouteImport.update({
  id: '/app-images',
  path: '/app-images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const ApiKycVerifyRoute = ApiKycVerifyRouteImport.update({
  id: '/api/kyc/verify',
  path: '/api/kyc/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/app-images': typeof AdminAppImagesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-followups': typeof AdminKycFollowupsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/diagnostics/routes': typeof DiagnosticsRoutesRoute
  '/preview/auth-phone': typeof PreviewAuthPhoneRoute
  '/preview/home': typeof PreviewHomeRoute
  '/preview/kyc-approved': typeof PreviewKycApprovedRoute
  '/preview/kyc-flow': typeof PreviewKycFlowRoute
  '/preview/kyc-pending': typeof PreviewKycPendingRoute
  '/preview/kyc-rejected': typeof PreviewKycRejectedRoute
  '/preview/onboarding': typeof PreviewOnboardingRoute
  '/preview/permissions': typeof PreviewPermissionsRoute
  '/preview/phone-verified': typeof PreviewPhoneVerifiedRoute
  '/preview/profile-help': typeof PreviewProfileHelpRoute
  '/preview/referral-program': typeof PreviewReferralProgramRoute
  '/preview/scan-pay': typeof PreviewScanPayRoute
  '/preview/splash': typeof PreviewSplashRoute
  '/admin/': typeof AdminIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/kyc/verify': typeof ApiKycVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/app-images': typeof AdminAppImagesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-followups': typeof AdminKycFollowupsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/diagnostics/routes': typeof DiagnosticsRoutesRoute
  '/preview/auth-phone': typeof PreviewAuthPhoneRoute
  '/preview/home': typeof PreviewHomeRoute
  '/preview/kyc-approved': typeof PreviewKycApprovedRoute
  '/preview/kyc-flow': typeof PreviewKycFlowRoute
  '/preview/kyc-pending': typeof PreviewKycPendingRoute
  '/preview/kyc-rejected': typeof PreviewKycRejectedRoute
  '/preview/onboarding': typeof PreviewOnboardingRoute
  '/preview/permissions': typeof PreviewPermissionsRoute
  '/preview/phone-verified': typeof PreviewPhoneVerifiedRoute
  '/preview/profile-help': typeof PreviewProfileHelpRoute
  '/preview/referral-program': typeof PreviewReferralProgramRoute
  '/preview/scan-pay': typeof PreviewScanPayRoute
  '/preview/splash': typeof PreviewSplashRoute
  '/admin': typeof AdminIndexRoute
  '/preview': typeof PreviewIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/kyc/verify': typeof ApiKycVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/app-images': typeof AdminAppImagesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cohorts': typeof AdminCohortsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/geo': typeof AdminGeoRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/kyc-followups': typeof AdminKycFollowupsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/diagnostics/routes': typeof DiagnosticsRoutesRoute
  '/preview/auth-phone': typeof PreviewAuthPhoneRoute
  '/preview/home': typeof PreviewHomeRoute
  '/preview/kyc-approved': typeof PreviewKycApprovedRoute
  '/preview/kyc-flow': typeof PreviewKycFlowRoute
  '/preview/kyc-pending': typeof PreviewKycPendingRoute
  '/preview/kyc-rejected': typeof PreviewKycRejectedRoute
  '/preview/onboarding': typeof PreviewOnboardingRoute
  '/preview/permissions': typeof PreviewPermissionsRoute
  '/preview/phone-verified': typeof PreviewPhoneVerifiedRoute
  '/preview/profile-help': typeof PreviewProfileHelpRoute
  '/preview/referral-program': typeof PreviewReferralProgramRoute
  '/preview/scan-pay': typeof PreviewScanPayRoute
  '/preview/splash': typeof PreviewSplashRoute
  '/admin/': typeof AdminIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/kyc/verify': typeof ApiKycVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/onboarding'
    | '/admin/admins'
    | '/admin/app-images'
    | '/admin/campaigns'
    | '/admin/cohorts'
    | '/admin/diagnostics'
    | '/admin/fraud'
    | '/admin/geo'
    | '/admin/health'
    | '/admin/kyc'
    | '/admin/kyc-followups'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet'
    | '/diagnostics/routes'
    | '/preview/auth-phone'
    | '/preview/home'
    | '/preview/kyc-approved'
    | '/preview/kyc-flow'
    | '/preview/kyc-pending'
    | '/preview/kyc-rejected'
    | '/preview/onboarding'
    | '/preview/permissions'
    | '/preview/phone-verified'
    | '/preview/profile-help'
    | '/preview/referral-program'
    | '/preview/scan-pay'
    | '/preview/splash'
    | '/admin/'
    | '/preview/'
    | '/admin/users/$id'
    | '/api/kyc/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/onboarding'
    | '/admin/admins'
    | '/admin/app-images'
    | '/admin/campaigns'
    | '/admin/cohorts'
    | '/admin/diagnostics'
    | '/admin/fraud'
    | '/admin/geo'
    | '/admin/health'
    | '/admin/kyc'
    | '/admin/kyc-followups'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet'
    | '/diagnostics/routes'
    | '/preview/auth-phone'
    | '/preview/home'
    | '/preview/kyc-approved'
    | '/preview/kyc-flow'
    | '/preview/kyc-pending'
    | '/preview/kyc-rejected'
    | '/preview/onboarding'
    | '/preview/permissions'
    | '/preview/phone-verified'
    | '/preview/profile-help'
    | '/preview/referral-program'
    | '/preview/scan-pay'
    | '/preview/splash'
    | '/admin'
    | '/preview'
    | '/admin/users/$id'
    | '/api/kyc/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/home'
    | '/onboarding'
    | '/admin/admins'
    | '/admin/app-images'
    | '/admin/campaigns'
    | '/admin/cohorts'
    | '/admin/diagnostics'
    | '/admin/fraud'
    | '/admin/geo'
    | '/admin/health'
    | '/admin/kyc'
    | '/admin/kyc-followups'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallet'
    | '/diagnostics/routes'
    | '/preview/auth-phone'
    | '/preview/home'
    | '/preview/kyc-approved'
    | '/preview/kyc-flow'
    | '/preview/kyc-pending'
    | '/preview/kyc-rejected'
    | '/preview/onboarding'
    | '/preview/permissions'
    | '/preview/phone-verified'
    | '/preview/profile-help'
    | '/preview/referral-program'
    | '/preview/scan-pay'
    | '/preview/splash'
    | '/admin/'
    | '/preview/'
    | '/admin/users/$id'
    | '/api/kyc/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  DiagnosticsRoutesRoute: typeof DiagnosticsRoutesRoute
  PreviewAuthPhoneRoute: typeof PreviewAuthPhoneRoute
  PreviewHomeRoute: typeof PreviewHomeRoute
  PreviewKycApprovedRoute: typeof PreviewKycApprovedRoute
  PreviewKycFlowRoute: typeof PreviewKycFlowRoute
  PreviewKycPendingRoute: typeof PreviewKycPendingRoute
  PreviewKycRejectedRoute: typeof PreviewKycRejectedRoute
  PreviewOnboardingRoute: typeof PreviewOnboardingRoute
  PreviewPermissionsRoute: typeof PreviewPermissionsRoute
  PreviewPhoneVerifiedRoute: typeof PreviewPhoneVerifiedRoute
  PreviewProfileHelpRoute: typeof PreviewProfileHelpRoute
  PreviewReferralProgramRoute: typeof PreviewReferralProgramRoute
  PreviewScanPayRoute: typeof PreviewScanPayRoute
  PreviewSplashRoute: typeof PreviewSplashRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
  ApiKycVerifyRoute: typeof ApiKycVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/preview'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/preview/splash': {
      id: '/preview/splash'
      path: '/preview/splash'
      fullPath: '/preview/splash'
      preLoaderRoute: typeof PreviewSplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/scan-pay': {
      id: '/preview/scan-pay'
      path: '/preview/scan-pay'
      fullPath: '/preview/scan-pay'
      preLoaderRoute: typeof PreviewScanPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/referral-program': {
      id: '/preview/referral-program'
      path: '/preview/referral-program'
      fullPath: '/preview/referral-program'
      preLoaderRoute: typeof PreviewReferralProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/profile-help': {
      id: '/preview/profile-help'
      path: '/preview/profile-help'
      fullPath: '/preview/profile-help'
      preLoaderRoute: typeof PreviewProfileHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/phone-verified': {
      id: '/preview/phone-verified'
      path: '/preview/phone-verified'
      fullPath: '/preview/phone-verified'
      preLoaderRoute: typeof PreviewPhoneVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/permissions': {
      id: '/preview/permissions'
      path: '/preview/permissions'
      fullPath: '/preview/permissions'
      preLoaderRoute: typeof PreviewPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/onboarding': {
      id: '/preview/onboarding'
      path: '/preview/onboarding'
      fullPath: '/preview/onboarding'
      preLoaderRoute: typeof PreviewOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/kyc-rejected': {
      id: '/preview/kyc-rejected'
      path: '/preview/kyc-rejected'
      fullPath: '/preview/kyc-rejected'
      preLoaderRoute: typeof PreviewKycRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/kyc-pending': {
      id: '/preview/kyc-pending'
      path: '/preview/kyc-pending'
      fullPath: '/preview/kyc-pending'
      preLoaderRoute: typeof PreviewKycPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/kyc-flow': {
      id: '/preview/kyc-flow'
      path: '/preview/kyc-flow'
      fullPath: '/preview/kyc-flow'
      preLoaderRoute: typeof PreviewKycFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/kyc-approved': {
      id: '/preview/kyc-approved'
      path: '/preview/kyc-approved'
      fullPath: '/preview/kyc-approved'
      preLoaderRoute: typeof PreviewKycApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/home': {
      id: '/preview/home'
      path: '/preview/home'
      fullPath: '/preview/home'
      preLoaderRoute: typeof PreviewHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/auth-phone': {
      id: '/preview/auth-phone'
      path: '/preview/auth-phone'
      fullPath: '/preview/auth-phone'
      preLoaderRoute: typeof PreviewAuthPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics/routes': {
      id: '/diagnostics/routes'
      path: '/diagnostics/routes'
      fullPath: '/diagnostics/routes'
      preLoaderRoute: typeof DiagnosticsRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc-followups': {
      id: '/admin/kyc-followups'
      path: '/kyc-followups'
      fullPath: '/admin/kyc-followups'
      preLoaderRoute: typeof AdminKycFollowupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geo': {
      id: '/admin/geo'
      path: '/geo'
      fullPath: '/admin/geo'
      preLoaderRoute: typeof AdminGeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cohorts': {
      id: '/admin/cohorts'
      path: '/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AdminCohortsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/app-images': {
      id: '/admin/app-images'
      path: '/app-images'
      fullPath: '/admin/app-images'
      preLoaderRoute: typeof AdminAppImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/kyc/verify': {
      id: '/api/kyc/verify'
      path: '/api/kyc/verify'
      fullPath: '/api/kyc/verify'
      preLoaderRoute: typeof ApiKycVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAppImagesRoute: typeof AdminAppImagesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCohortsRoute: typeof AdminCohortsRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminGeoRoute: typeof AdminGeoRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminKycFollowupsRoute: typeof AdminKycFollowupsRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAppImagesRoute: AdminAppImagesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCohortsRoute: AdminCohortsRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminGeoRoute: AdminGeoRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminKycRoute: AdminKycRoute,
  AdminKycFollowupsRoute: AdminKycFollowupsRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  DiagnosticsRoutesRoute: DiagnosticsRoutesRoute,
  PreviewAuthPhoneRoute: PreviewAuthPhoneRoute,
  PreviewHomeRoute: PreviewHomeRoute,
  PreviewKycApprovedRoute: PreviewKycApprovedRoute,
  PreviewKycFlowRoute: PreviewKycFlowRoute,
  PreviewKycPendingRoute: PreviewKycPendingRoute,
  PreviewKycRejectedRoute: PreviewKycRejectedRoute,
  PreviewOnboardingRoute: PreviewOnboardingRoute,
  PreviewPermissionsRoute: PreviewPermissionsRoute,
  PreviewPhoneVerifiedRoute: PreviewPhoneVerifiedRoute,
  PreviewProfileHelpRoute: PreviewProfileHelpRoute,
  PreviewReferralProgramRoute: PreviewReferralProgramRoute,
  PreviewScanPayRoute: PreviewScanPayRoute,
  PreviewSplashRoute: PreviewSplashRoute,
  PreviewIndexRoute: PreviewIndexRoute,
  ApiKycVerifyRoute: ApiKycVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
